config/routes.rb
Rails.application.routes.draw do
  get 'homes/login'
  post "homes/login_attempt"
  get 'stocks/admin'

  resources :stocks do
     collection { 
       post :import 
       get :search
     }
  end

  resources :promos

  resources :product_groups

  resources :product_categories

  resources :brands

  resources :admins
  
  post 'welcome_email' => 'welcome_email#create'
  post 'update_stock' => 'stocks#update_stock'
  
  root to: "homes#login"

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  
  require 'csv'
  belongs_to :product_group
  belongs_to :brand
  has_many :promos
 # mount_uploader :picture, PictureUploader
  belongs_to :parent_stock, foreign_key: 'parent_id', class_name: 'Stock'
  accepts_nested_attributes_for :brand, :product_group, :promos
#  INDEX_PARENTSKUID	= 1
#  INDEX_PARENTSKUNAME	= 2
#  INDEX_SKUNAME	= 3
#  INDEX_SKUNAMEADDITIONALTEXT	= 4
#  INDEX_NORMALPRICE	= 5
#  INDEX_STORENAME	= 6
#  INDEX_PRODUCTCATEGORY	= 7
#  INDEX_PRODUCTGROUP	= 8
#  INDEX_PRODUCTTYPE	= 9
#  INDEX_STATUS = 10
#  INDEX_MANUFACTURER = 11
#  INDEX_BRAND = 12	
#  INDEX_PACKAGING = 13	
#  INDEX_UNITSOFITEM = 14
#  INDEX_TEKAPOSIZE = 15
#  INDEX_PROMOTYPE = 16
#  INDEX_PROMOENDDATE = 17
#  INDEX_HALALSTATUS = 18	
#  INDEX_HALALCERTIFICATIONISSUER = 19
#  INDEX_PRESERVATIVESSTATUS = 20
#  INDEX_ARTIFICIALCOLORINGSTATUS = 21
#  INDEX_ARTIFICIALFLAVORINGSTATUS = 22	
#  INDEX_FOODCONDITIONERSTATUS = 23
#  INDEX_ARTIFICIALSWEETENERSTATUS = 24
#  INDEX_RETURNABLE = 25
#  INDEX_TEKAPOPRODUCTNOTE = 26
#  INDEX_TEKAPOINTERNALNOTE = 27	
#  INDEX_PRODUCTPRICEGROUP = 28
#  INDEX_SKUDATECREATED = 29
#  INDEX_SKUCREATOR = 30
#  INDEX_SKUDATELASTUPDATED = 31
  
  def self.import(file, options = {:headers => true, :col_sep => ','} )
    stocks = []
    unless file.nil?
      puts "File is not nil #{file.path} | #{options}"
      CSV.foreach(file.path, options) do |row|
        
        parent_stock = Stock.find_or_create_by(
            name: row['parentSkuName'], store_name: nil)
        
        if row['parentSkuName'].present?
          parent_stock_id = parent_stock.id
        else
          parent_stock_id = parent_stock.id
        end
        
        stock = Stock.find_or_create_by!(
          name: row['skuName'], 
          store_name: row['storeName'], 
          parent_id: parent_stock_id
        ) if row['skuName'].present?
        stocks << stock
        
        stock.additional_text = row['skuNameAdditionalText']
        stock.normal_price = row['normalPrice']
        stock.store_name = row['storeName']
        
        if row['productCategory'].present?
          product_category = ProductCategory.find_or_create_by!(
            name: row['productCategory']
          ) 
          product_category_id = product_category.id
        else
          product_category_id = nil
        end
        
        stock.product_group = ProductGroup.find_or_create_by!(
          name: row['productGroup'],
          product_type: row['productType'],
          product_category_id: product_category_id
        ) if row['productGroup'].present? || row['productType'].present?
        
        stock.status = row['status']
        
        stock.brand = Brand.find_or_create_by!(
          name: row['brand'],
          manufacturer: row['manufacturer']
        ) if row['brand'].present? || row['manufacturer'].present?
        
        stock.packaging = row['packaging']
        stock.units_of_item = row['unitsOfItem']
        stock.size = row['tekapoSize']
        
        if row['promoType'].present?
          stock.promos << [Promo.find_or_create_by!(
            promo_type: row['promoType'],
            end_date: row['promoEndDate']
          )]
        end
  
        stock.halal_status = row['halalStatus']
        stock.halal_certification_issuer = row['halalCertificationIssuer']
        stock.preservatives_status = row['preservativesStatus']
        stock.artificial_coloring_status = row['artificialColoringStatus']
        stock.artificial_flavoring_status = row['artificialFlavoringStatus']
        stock.food_conditioner_status = row['foodConditionerStatus']
        stock.artifical_sweetener_status = row['artificialSweetenerStatus']
        stock.returnable = row['returnable']
        stock.product_note = row['tekapoProductNote']
        stock.internal_note = row['tekapoInternalNote']
        stock.product_price_group = row['productPriceGroup']
        stock.created_at = row['skuDateCreated']
        stock.creator = row['skuCreator'] || 'admin'
        stock.updated_at = row['skuDateLastUpdated']
        stock.save!
      end
    end
    stocks  
  end
  
  def self.update_edit(params)
        
    stock = Stock.find_by_id(params['id'])

    if stock
      stock.store_name = params['store_name'];
      stock.normal_price = params['normal_price'];
      stock.parent_id = params['parent_id'];
      stock.halal_status = params['halal_status'];
      stock.picture = params['picture'];
      stock.halal_certification_issuer = params['halal_certification_issuer'];
      stock.creator = params['creator'];
      stock.additional_text = params['additional_text'];
      stock.preservatives_status = params['preservatives_status'];
      stock.product_note = params['product_note'];
      stock.artificial_coloring_status = params['artificial_coloring_status'];
      stock.size = params['size'];
      stock.product_group_id = params['product_group_id'];
      stock.food_conditioner_status = params['food_conditioner_status'];
      stock.units_of_item = params['units_of_item'];
      stock.status = params['status'];
      stock.artifical_sweetener_status = params['artifical_sweetener_status'];
      stock.internal_note = params['internal_note'];
      stock.brand = params['brand'];
      stock.returnable = params['returnable'];
      stock.packaging = params['packaging'];
      stock.product_price_group = params['product_price_group'];
      stock.artificial_flavoring_status = params['artificial_flavoring_status'];
      
      stock.save!

    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  #respond_to :json, :html
  # GET /stocks
  # GET /stocks.json
  
  def index
    @stocks = Stock.all
    respond_to do |format|
      format.html {@stocks}
      format.json {render json: @stocks.as_json}
    end
  end
  
  def search
    @stocks = []
    @stocks = ThinkingSphinx.search params[:search] if params[:search]        
    respond_to do |format| 
      format.html {render :layout => false}
      format.json {render json: @stocks.as_json}
    end
    
  end  

  def search
    @stocks = []
    @stocks = ThinkingSphinx.search params[:search] if params[:search]        
  end

  
    # GET /stocks/1
    # GET /stocks/1.json
    def show
      respond_to do |format|
        format.html {@stock}
        format.json {render json: @stock.as_json}
      end
    end

    # GET /stocks/new
    def new
      @stock = Stock.new
    end

    # GET /stocks/1/edit
    def edit
    end

    # POST /stocks
    # POST /stocks.json
    def create
      @stock = Stock.new(stock_params)

      respond_to do |format|
        if @stock.save
          format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
          format.json { render :show, status: :created, location: @stock }
        else
          format.html { render :new }
          format.json { render json: @stock.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /stocks/1
    # PATCH/PUT /stocks/1.json
    def update
      respond_to do |format|
        if @stock.update(stock_params)
          format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
          format.json { render :show, status: :ok, location: @stock }
        else
          format.html { render :edit }
          format.json { render json: @stock.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /stocks/1
    # DELETE /stocks/1.json
    def destroy
      @stock.destroy
      respond_to do |format|
        format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    def import
      begin
        Stock.import(params[:file])
        redirect_to :back, notice: "Products imported."
      rescue
        redirect_to :back, notice: "Invalid CSV file format."
      end
    end

  def update_stock
    update_record = Stock.update_edit(params)  
  end
  
  def admin
    @stocks = Stock.all
    respond_to do |format|
      format.html {@stocks}
      format.json {render json: @stocks.as_json}
    end
  end  
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:parent_id, :name, :additional_text, :normal_price, :store_name, :product_group_id, :status, :brand_id, :packaging, :units_of_item, :size, :halal_status, :halal_certification_issuer, :preservatives_status, :artificial_coloring_status, :artificial_flavoring_status, :food_conditioner_status, :artifical_sweetener_status, :returnable, :product_note, :internal_note, :product_price_group, :creator, :picture)
    end
  end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :additional_text %><br>
    <%= f.text_area :additional_text %>
  </div>
  <div class="field">
    <%= f.label :normal_price %><br>
    <%= f.text_field :normal_price %>
  </div>
  <div class="field">
    <%= f.label :store_name %><br>
    <%= f.text_field :store_name %>
  </div>
  <div class="field">
    <%= f.label :product_group_id %><br>
    <%= f.number_field :product_group_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.number_field :brand_id %>
  </div>
  <div class="field">
    <%= f.label :packaging %><br>
    <%= f.text_field :packaging %>
  </div>
  <div class="field">
    <%= f.label :units_of_item %><br>
    <%= f.number_field :units_of_item %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :halal_status %><br>
    <%= f.text_field :halal_status %>
  </div>
  <div class="field">
    <%= f.label :halal_certification_issuer %><br>
    <%= f.text_field :halal_certification_issuer %>
  </div>
  <div class="field">
    <%= f.label :preservatives_status %><br>
    <%= f.text_field :preservatives_status %>
  </div>
  <div class="field">
    <%= f.label :artificial_coloring_status %><br>
    <%= f.text_field :artificial_coloring_status %>
  </div>
  <div class="field">
    <%= f.label :artificial_flavoring_status %><br>
    <%= f.text_field :artificial_flavoring_status %>
  </div>
  <div class="field">
    <%= f.label :food_conditioner_status %><br>
    <%= f.text_field :food_conditioner_status %>
  </div>
  <div class="field">
    <%= f.label :artifical_sweetener_status %><br>
    <%= f.text_field :artifical_sweetener_status %>
  </div>
  <div class="field">
    <%= f.label :returnable %><br>
    <%= f.check_box :returnable %>
  </div>
  <div class="field">
    <%= f.label :product_note %><br>
    <%= f.text_field :product_note %>
  </div>
  <div class="field">
    <%= f.label :internal_note %><br>
    <%= f.text_field :internal_note %>
  </div>
  <div class="field">
    <%= f.label :product_price_group %><br>
    <%= f.text_field :product_price_group %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/admin.html.erb
<script type="text/x-handlebars">

 <h3> &nbsp; Welcome to the Grocery website</h3>

<nav class="top-bar" data-topbar>
  <section class="top-bar-section">

    <!-- Left Nav Section -->
    <ul class="left">
      <li class="active"><%= link_to 'New Stock', new_stock_path %><li>
      <li>{{#linkTo 'admin'}}Edit stocks{{/linkTo}}</li>
    </ul>
  </section>
</nav>
{{outlet}}
</script>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<%= link_to 'New Stock', new_stock_path %>
<%= link_to 'Search Stock', search_stocks_path %>

<script type="text/x-handlebars">

<h1> Welcome </h1>
{{#linkTo 'posts'}}Posts{{/linkTo}}  
{{#linkTo 'about'}}About{{/linkTo}}
{{#linkTo 'stocks'}}View stocks{{/linkTo}}
  
              {{outlet}}

</script>



  <tbody>
    <%# @stocks.each do |stock| %>
      <%#*<tr>%>
        <%#*<td><%= stock.parent_id %></td>%>
        <%#*<td><%= stock.name %></td>%>
        <%#*<td><%= stock.additional_text %></td>%>
        <%#*<td><%= stock.normal_price %></td>%>
        <%#*<td><%= stock.store_name %></td>%>
        <%#*<td><%= stock.product_group_id %></td>%>
        <%#*<td><%= stock.status %></td>%>
        <%#*<td><%= stock.brand_id %></td>%>
        <%#*<td><%= stock.packaging %></td>%>
        <%#*<td><%= stock.units_of_item %></td>%>
        <%#*<td><%= stock.size %></td>%>
        <%#*<td><%= stock.halal_status %></td>%>
        <%#*<td><%= stock.halal_certification_issuer %></td>%>
        <%#*<td><%= stock.preservatives_status %></td>%>
        <%#*<td><%= stock.artificial_coloring_status %></td>%>
        <%#*<td><%= stock.artificial_flavoring_status %></td>%>
        <%#*<td><%= stock.food_conditioner_status %></td>%>
        <%#*<td><%= stock.artifical_sweetener_status %></td>%>
        <%#*<td><%= stock.returnable %></td>%>
        <%#*<td><%= stock.product_note %></td>%>
        <%#*<td><%= stock.internal_note %></td>%>
        <%#*<td><%= stock.product_price_group %></td>%>
        <%#*<td><%= stock.creator %></td>%>
        <%#*<td><%= stock.picture %></td>%>
        <%#*<td><%= link_to 'Show', stock %></td>%>
        <%#*<td><%= link_to 'Edit', edit_stock_path(stock) %></td>%>
        <%#*<td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>%>
      <%#*</tr>%>
    <%# end %>
  </tbody>
</table>

<script type="text/x-handlebars" id="index">
          <br><br>
     <h3 class="headline"> Your groceries 
     <br>
     delivered. Tomorrow. </h3>
     <p class="tagline"> Pick your groceries. </p>
     {{#link-to 'stocks' class="button" id="custombutton"}} Search groceries now. {{/link-to}}
</script>

<%#*<form id="live-search-form" method="get" action="<%= search_stocks_path %>">%>
  <%#*<input id="big-search-box" name="search" placeholder="Search product" type="text"/>%>
<%#*</form>%>

<%#*<div id="live-search-results"></div>%>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= flash[:notice] %>

<div>
<h3>Import a CSV File</h3>
  <%= form_tag import_stocks_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<%#= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/search.html.erb
<%= link_to 'Menu', "/stocks" %>

<%= form_tag search_stocks_path, :method => :get do  %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<%unless @stocks.blank?%>
  <h1>Listing stocks</h1>
  <table>
    <thead>
      <tr>
        <th>Parent</th>
        <th>Name</th>
        <th>Additional text</th>
        <th>Normal price</th>
        <th>Store name</th>
        <th>Product group</th>
        <th>Status</th>
        <th>Brand</th>
        <th>Packaging</th>
        <th>Units of item</th>
        <th>Size</th>
        <th>Halal status</th>
        <th>Halal certification issuer</th>
        <th>Preservatives status</th>
        <th>Artificial coloring status</th>
        <th>Artificial flavoring status</th>
        <th>Food conditioner status</th>
        <th>Artifical sweetener status</th>
        <th>Returnable</th>
        <th>Product note</th>
        <th>Internal note</th>
        <th>Product price group</th>
        <th>Creator</th>
        <th>Picture</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= stock.parent_id %></td>
          <td><%= stock.name %></td>
          <td><%= stock.additional_text %></td>
          <td><%= stock.normal_price %></td>
          <td><%= stock.store_name %></td>
          <td><%= stock.product_group_id %></td>
          <td><%= stock.status %></td>
          <td><%= stock.brand_id %></td>
          <td><%= stock.packaging %></td>
          <td><%= stock.units_of_item %></td>
          <td><%= stock.size %></td>
          <td><%= stock.halal_status %></td>
          <td><%= stock.halal_certification_issuer %></td>
          <td><%= stock.preservatives_status %></td>
          <td><%= stock.artificial_coloring_status %></td>
          <td><%= stock.artificial_flavoring_status %></td>
          <td><%= stock.food_conditioner_status %></td>
          <td><%= stock.artifical_sweetener_status %></td>
          <td><%= stock.returnable %></td>
          <td><%= stock.product_note %></td>
          <td><%= stock.internal_note %></td>
          <td><%= stock.product_price_group %></td>
          <td><%= stock.creator %></td>
          <td><%= stock.picture %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%end%>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent:</strong>
  <%= @stock.parent_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Additional text:</strong>
  <%= @stock.additional_text %>
</p>

<p>
  <strong>Normal price:</strong>
  <%= @stock.normal_price %>
</p>

<p>
  <strong>Store name:</strong>
  <%= @stock.store_name %>
</p>

<p>
  <strong>Product group:</strong>
  <%= @stock.product_group_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @stock.status %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @stock.brand_id %>
</p>

<p>
  <strong>Packaging:</strong>
  <%= @stock.packaging %>
</p>

<p>
  <strong>Units of item:</strong>
  <%= @stock.units_of_item %>
</p>

<p>
  <strong>Size:</strong>
  <%= @stock.size %>
</p>

<p>
  <strong>Halal status:</strong>
  <%= @stock.halal_status %>
</p>

<p>
  <strong>Halal certification issuer:</strong>
  <%= @stock.halal_certification_issuer %>
</p>

<p>
  <strong>Preservatives status:</strong>
  <%= @stock.preservatives_status %>
</p>

<p>
  <strong>Artificial coloring status:</strong>
  <%= @stock.artificial_coloring_status %>
</p>

<p>
  <strong>Artificial flavoring status:</strong>
  <%= @stock.artificial_flavoring_status %>
</p>

<p>
  <strong>Food conditioner status:</strong>
  <%= @stock.food_conditioner_status %>
</p>

<p>
  <strong>Artifical sweetener status:</strong>
  <%= @stock.artifical_sweetener_status %>
</p>

<p>
  <strong>Returnable:</strong>
  <%= @stock.returnable %>
</p>

<p>
  <strong>Product note:</strong>
  <%= @stock.product_note %>
</p>

<p>
  <strong>Internal note:</strong>
  <%= @stock.internal_note %>
</p>

<p>
  <strong>Product price group:</strong>
  <%= @stock.product_price_group %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @stock.creator %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @stock.picture %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/update_stock.html.erb
<h1>Editing stock</h1>