config/routes.rb
Rails.application.routes.draw do
  get 'homes/login'
  post "homes/login_attempt"
  get 'stocks/admin'

  resources :stocks do
     collection { 
       post :import 
       get :search
     }
  end

  resources :promos

  resources :product_groups

  resources :product_categories

  resources :brands

  resources :admins
  
  post 'welcome_email' => 'welcome_email#create'
  post 'update_stock' => 'stocks#update_stock'
  
  root to: "homes#login"

end

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
  before_action :set_product_group, only: [:show, :edit, :update, :destroy]

  # GET /product_groups
  # GET /product_groups.json
  def index
    @product_groups = ProductGroup.all
  end

  # GET /product_groups/1
  # GET /product_groups/1.json
  def show
  end

  # GET /product_groups/new
  def new
    @product_group = ProductGroup.new
  end

  # GET /product_groups/1/edit
  def edit
  end

  # POST /product_groups
  # POST /product_groups.json
  def create
    @product_group = ProductGroup.new(product_group_params)

    respond_to do |format|
      if @product_group.save
        format.html { redirect_to @product_group, notice: 'Product group was successfully created.' }
        format.json { render :show, status: :created, location: @product_group }
      else
        format.html { render :new }
        format.json { render json: @product_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_groups/1
  # PATCH/PUT /product_groups/1.json
  def update
    respond_to do |format|
      if @product_group.update(product_group_params)
        format.html { redirect_to @product_group, notice: 'Product group was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_group }
      else
        format.html { render :edit }
        format.json { render json: @product_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_groups/1
  # DELETE /product_groups/1.json
  def destroy
    @product_group.destroy
    respond_to do |format|
      format.html { redirect_to product_groups_url, notice: 'Product group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_group
      @product_group = ProductGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_group_params
      params.require(:product_group).permit(:name, :product_type, :product_category_id)
    end
end

app/helpers/product_groups_helper.rb
module ProductGroupsHelper
end

app/views/product_groups/_form.html.erb
<%= form_for(@product_group) do |f| %>
  <% if @product_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

      <ul>
      <% @product_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :product_category_id %><br>
    <%= f.number_field :product_category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_groups/edit.html.erb
<h1>Editing product_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_group %> |
<%= link_to 'Back', product_groups_path %>

app/views/product_groups/index.html.erb
<h1>Listing product_groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product type</th>
      <th>Product category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_groups.each do |product_group| %>
      <tr>
        <td><%= product_group.name %></td>
        <td><%= product_group.product_type %></td>
        <td><%= product_group.product_category_id %></td>
        <td><%= link_to 'Show', product_group %></td>
        <td><%= link_to 'Edit', edit_product_group_path(product_group) %></td>
        <td><%= link_to 'Destroy', product_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product group', new_product_group_path %>

app/views/product_groups/new.html.erb
<h1>New product_group</h1>

<%= render 'form' %>

<%= link_to 'Back', product_groups_path %>

app/views/product_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_group.name %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @product_group.product_type %>
</p>

<p>
  <strong>Product category:</strong>
  <%= @product_group.product_category_id %>
</p>

<%= link_to 'Edit', edit_product_group_path(@product_group) %> |
<%= link_to 'Back', product_groups_path %>