config/routes.rb
Rails.application.routes.draw do
  get 'homes/login'
  post "homes/login_attempt"
  get 'stocks/admin'

  resources :stocks do
     collection { 
       post :import 
       get :search
     }
  end

  resources :promos

  resources :product_groups

  resources :product_categories

  resources :brands

  resources :admins
  
  post 'welcome_email' => 'welcome_email#create'
  post 'update_stock' => 'stocks#update_stock'
  
  root to: "homes#login"

end

app/models/promo.rb
class Promo < ActiveRecord::Base
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:promo_type, :end_date, :stock_id)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for(@promo) do |f| %>
  <% if @promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% @promo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :promo_type %><br>
    <%= f.text_area :promo_type %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.number_field :stock_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<h1>Listing promos</h1>

<table>
  <thead>
    <tr>
      <th>Promo type</th>
      <th>End date</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promos.each do |promo| %>
      <tr>
        <td><%= promo.promo_type %></td>
        <td><%= promo.end_date %></td>
        <td><%= promo.stock_id %></td>
        <td><%= link_to 'Show', promo %></td>
        <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
        <td><%= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<h1>New promo</h1>

<%= render 'form' %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Promo type:</strong>
  <%= @promo.promo_type %>
</p>

<p>
  <strong>End date:</strong>
  <%= @promo.end_date %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @promo.stock_id %>
</p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>